# Generated by Django 3.1.7 on 2021-03-11 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_delete_choise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pub_date',
        ),
    ]
