# Generated by Django 3.1.7 on 2021-03-11 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_question_pub_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
