# Generated by Django 3.1.7 on 2021-03-14 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210314_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_qanswer', models.TextField()),
                ('is_correct', models.BooleanField()),
                ('create_tamp', models.DateTimeField(auto_now_add=True)),
                ('edit_tamp', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_category', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_question', models.TextField()),
                ('create_tamp', models.DateTimeField(auto_now_add=True)),
                ('edit_tamp', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
            ],
        ),
        migrations.CreateModel(
            name='Tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_test', models.CharField(max_length=50)),
                ('create_tamp', models.DateTimeField(auto_now_add=True)),
                ('edit_tamp', models.DateTimeField(auto_now=True)),
                ('category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories')),
            ],
        ),
        migrations.RenameField(
            model_name='users',
            old_name='update_tamp',
            new_name='edit_tamp',
        ),
        migrations.CreateModel(
            name='Users_tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(blank=True)),
                ('create_tamp', models.DateTimeField(auto_now_add=True)),
                ('edit_tamp', models.DateTimeField(auto_now=True)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tests')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
        migrations.CreateModel(
            name='Users_answers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_tamp', models.DateTimeField(auto_now_add=True)),
                ('edit_tamp', models.DateTimeField(auto_now=True)),
                ('answer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.answers')),
                ('user_test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users_tests')),
            ],
        ),
        migrations.CreateModel(
            name='Tests_questions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_tamp', models.DateTimeField(auto_now_add=True)),
                ('edit_tamp', models.DateTimeField(auto_now=True)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions')),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tests')),
            ],
        ),
        migrations.AddField(
            model_name='questions',
            name='created_by_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users'),
        ),
        migrations.AddField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions'),
        ),
    ]
