# Generated by Django 3.1.7 on 2021-03-14 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210314_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='create_tamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='answers',
            old_name='edit_tamp',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='create_tamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='questions',
            old_name='edit_tamp',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='create_tamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tests',
            old_name='edit_tamp',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='tests_questions',
            old_name='create_tamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='tests_questions',
            old_name='edit_tamp',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='create_tamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='users',
            old_name='edit_tamp',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='users_answers',
            old_name='create_tamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='users_answers',
            old_name='edit_tamp',
            new_name='updated_at',
        ),
        migrations.RenameField(
            model_name='users_tests',
            old_name='create_tamp',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='users_tests',
            old_name='edit_tamp',
            new_name='updated_at',
        ),
    ]
