# Generated by Django 3.1.7 on 2021-03-14 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210314_1326'),
    ]

    operations = [
        migrations.RenameField(
            model_name='answers',
            old_name='text_qanswer',
            new_name='text_answer',
        ),
    ]
