# Generated by Django 3.1.7 on 2021-03-14 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210314_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answers',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions', verbose_name='question'),
        ),
        migrations.AlterField(
            model_name='questions',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories', verbose_name='category'),
        ),
    ]
