# Generated by Django 3.1.7 on 2021-03-15 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_auto_20210315_0905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests_questions',
            name='question_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.questions', verbose_name='question'),
        ),
    ]
