# Generated by Django 3.1.7 on 2021-03-15 18:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20210315_1156'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tests_questions',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tests', verbose_name='test'),
        ),
    ]
