# Generated by Django 3.1.7 on 2021-03-19 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_auto_20210315_2037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users_answers',
            name='answer_id',
        ),
        migrations.RemoveField(
            model_name='users_answers',
            name='user_test_id',
        ),
        migrations.RemoveField(
            model_name='users_tests',
            name='test_id',
        ),
        migrations.RemoveField(
            model_name='users_tests',
            name='user_id',
        ),
        migrations.AddField(
            model_name='answers',
            name='users',
            field=models.ManyToManyField(to='main.Users'),
        ),
        migrations.AddField(
            model_name='questions',
            name='tests',
            field=models.ManyToManyField(to='main.Tests'),
        ),
        migrations.AddField(
            model_name='tests',
            name='users',
            field=models.ManyToManyField(to='main.Users'),
        ),
        migrations.AlterField(
            model_name='tests',
            name='category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.categories', verbose_name='category'),
        ),
        migrations.DeleteModel(
            name='Tests_questions',
        ),
        migrations.DeleteModel(
            name='Users_answers',
        ),
        migrations.DeleteModel(
            name='Users_tests',
        ),
    ]
