# Generated by Django 3.1.7 on 2021-03-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_auto_20210319_2201'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questions',
            name='tests',
        ),
        migrations.AddField(
            model_name='tests',
            name='questions',
            field=models.ManyToManyField(to='main.Questions'),
        ),
    ]
