# Generated by Django 3.1.7 on 2021-03-20 14:33

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_auto_20210319_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tests',
            name='users',
        ),
        migrations.CreateModel(
            name='Users_tests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.FloatField(blank=True)),
                ('passed_questions', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('test_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.tests')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.users')),
            ],
        ),
    ]
